export const CUSTOM_IGNORE = [
	// Dependencies
	'node_modules/',
	'bower_components/',
	'jspm_packages/',
	'vendor/',
	'packages/',
	'.pnp/',
	'.pnp.js',
	
	// Build outputs
	'dist/',
	'build/',
	'out/',
	'target/',
	'bin/',
	'obj/',
	'lib/',
	'*.min.js',
	'*.min.css',
	'bundle.js',
	'bundle.css',
	'*.bundle.*',
	'compiled/',
	'generated/',
	
	// Cache directories
	'.cache/',
	'.parcel-cache/',
	'.next/',
	'.nuxt/',
	'.vuepress/dist/',
	'.serverless/',
	'.fusebox/',
	'.dynamodb/',
	'.tern-port',
	'.vscode-test',
	'.nyc_output',
	
	// Logs
	'logs/',
	'*.log',
	'npm-debug.log*',
	'yarn-debug.log*',
	'yarn-error.log*',
	'lerna-debug.log*',
	'.npm',
	'.eslintcache',
	'.stylelintcache',
	
	// Runtime data
	'pids/',
	'*.pid',
	'*.seed',
	'*.pid.lock',
	
	// Coverage directory used by tools like istanbul
	'coverage/',
	'*.lcov',
	'.nyc_output/',
	
	// Grunt intermediate storage
	'.grunt',
	
	// node-waf configuration
	'.lock-wscript',
	
	// Optional npm cache directory
	'.npm',
	
	// Optional eslint cache
	'.eslintcache',
	
	// Microbundle cache
	'.rpt2_cache/',
	'.rts2_cache_cjs/',
	'.rts2_cache_es/',
	'.rts2_cache_umd/',
	
	// Optional REPL history
	'.node_repl_history',
	
	// Output of 'npm pack'
	'*.tgz',
	
	// Yarn Integrity file
	'.yarn-integrity',
	
	// dotenv environment variables file
	'.env',
	'.env.local',
	'.env.development.local',
	'.env.test.local',
	'.env.production.local',
	'.env.*.local',
	
	// parcel-bundler cache
	'.parcel-cache/',
	
	// Next.js build output
	'.next/',
	'out/',
	
	// Nuxt.js build / generate output
	'.nuxt/',
	'dist/',
	
	// Gatsby files
	'.cache/',
	'public/',
	
	// Storybook build outputs
	'.out',
	'.storybook-out',
	'storybook-static/',
	
	// Temporary folders
	'tmp/',
	'temp/',
	'.tmp/',
	'.temp/',
	
	// OS generated files
	'.DS_Store',
	'.DS_Store?',
	'._*',
	'.Spotlight-V100',
	'.Trashes',
	'ehthumbs.db',
	'Thumbs.db',
	'Desktop.ini',
	'$RECYCLE.BIN/',
	
	// Editor directories and files
	'.vscode/',
	'!.vscode/settings.json',
	'!.vscode/tasks.json',
	'!.vscode/launch.json',
	'!.vscode/extensions.json',
	'*.swp',
	'*.swo',
	'*~',
	'.idea/',
	'*.iml',
	'*.ipr',
	'*.iws',
	'.sublime-project',
	'.sublime-workspace',
	'*.sublime-*',
	
	// Version control
	'.git/',
	'.svn/',
	'.hg/',
	'.bzr/',
	'CVS/',
	
	// Backup files
	'*.bak',
	'*.backup',
	'*.old',
	'*.orig',
	'*.tmp',
	
	// Compiled source
	'*.com',
	'*.class',
	'*.dll',
	'*.exe',
	'*.o',
	'*.so',
	'*.dylib',
	
	// Archives
	'*.7z',
	'*.dmg',
	'*.gz',
	'*.iso',
	'*.jar',
	'*.rar',
	'*.tar',
	'*.zip',
	'*.war',
	'*.ear',
	'*.sar',
	'*.class',
	
	// Python
	'__pycache__/',
	'*.py[cod]',
	'*$py.class',
	'*.so',
	'.Python',
	'build/',
	'develop-eggs/',
	'downloads/',
	'eggs/',
	'.eggs/',
	'lib/',
	'lib64/',
	'parts/',
	'sdist/',
	'var/',
	'wheels/',
	'*.egg-info/',
	'.installed.cfg',
	'*.egg',
	'MANIFEST',
	'*.manifest',
	'*.spec',
	'pip-log.txt',
	'pip-delete-this-directory.txt',
	'.tox/',
	'.coverage',
	'.pytest_cache/',
	'htmlcov/',
	'.cache',
	'nosetests.xml',
	'coverage.xml',
	'*.cover',
	'.hypothesis/',
	'.pytest_cache/',
	'celerybeat-schedule',
	'*.sage.py',
	'.env',
	'.venv',
	'env/',
	'venv/',
	'ENV/',
	'env.bak/',
	'venv.bak/',
	'.spyderproject',
	'.spyproject',
	'.ropeproject',
	'/site',
	'.mypy_cache/',
	'.dmypy.json',
	'dmypy.json',
	'.pyre/',
	
	// Java
	'*.class',
	'*.log',
	'*.ctxt',
	'.mtj.tmp/',
	'*.jar',
	'*.war',
	'*.nar',
	'*.ear',
	'*.zip',
	'*.tar.gz',
	'*.rar',
	'hs_err_pid*',
	'.gradle',
	'build/',
	'!gradle/wrapper/gradle-wrapper.jar',
	'!**/src/main/**/build/',
	'!**/src/test/**/build/',
	'.gradle/',
	'gradle-app.setting',
	'!gradle-wrapper.jar',
	'.gradletasknamecache',
	'target/',
	'pom.xml.tag',
	'pom.xml.releaseBackup',
	'pom.xml.versionsBackup',
	'pom.xml.next',
	'release.properties',
	'dependency-reduced-pom.xml',
	'buildNumber.properties',
	'.mvn/timing.properties',
	'.mvn/wrapper/maven-wrapper.jar',
	
	// C/C++
	'*.o',
	'*.ko',
	'*.obj',
	'*.elf',
	'*.ilk',
	'*.map',
	'*.exp',
	'*.gch',
	'*.pch',
	'*.lib',
	'*.a',
	'*.la',
	'*.lo',
	'*.dll',
	'*.so',
	'*.so.*',
	'*.dylib',
	'*.exe',
	'*.out',
	'*.app',
	'*.i*86',
	'*.x86_64',
	'*.hex',
	'.deps/',
	'.dirstamp',
	
	// C#
	'bin/',
	'obj/',
	'*.user',
	'*.aps',
	'*.pch',
	'*.vspscc',
	'*_i.c',
	'*_p.c',
	'*.ncb',
	'*.suo',
	'*.tlb',
	'*.tlh',
	'*.bak',
	'*.cache',
	'*.ilk',
	'*.log',
	'[Bb]in',
	'[Dd]ebug*/',
	'*.lib',
	'*.sbr',
	'obj/',
	'[Rr]elease*/',
	'_ReSharper*/',
	'[Tt]est[Rr]esult*',
	'*.vssscc',
	'$tf/',
	'*.user',
	'*.suo',
	'*.cache',
	'*.docstates',
	'_ReSharper.*/',
	'packages/',
	'artifacts/',
	'PublishProfiles/',
	'*.azurePubxml',
	'*.pubxml',
	'*.publishproj',
	
	// Go
	'*.exe',
	'*.exe~',
	'*.dll',
	'*.so',
	'*.dylib',
	'*.test',
	'*.out',
	'go.work',
	
	// Rust
	'target/',
	'**/*.rs.bk',
	'*.pdb',
	'Cargo.lock',
	
	// Ruby
	'*.gem',
	'*.rbc',
	'/.config',
	'/coverage/',
	'/InstalledFiles',
	'/pkg/',
	'/spec/reports/',
	'/spec/examples.txt',
	'/test/tmp/',
	'/test/version_tmp/',
	'/tmp/',
	'.bundle/',
	'vendor/bundle',
	'lib/bundler/man',
	'.rvmrc',
	'.rbenv-version',
	'.ruby-version',
	'.ruby-gemset',
	'.sass-cache/',
	'.jekyll-cache/',
	'.jekyll-metadata',
	
	// PHP
	'/vendor/',
	'node_modules/',
	'npm-debug.log',
	'yarn-error.log',
	'.env',
	'.env.backup',
	'.phpunit.result.cache',
	'Homestead.json',
	'Homestead.yaml',
	'auth.json',
	'*.cache',
	'*.log',
	
	// Laravel specific
	'/bootstrap/compiled.php',
	'/app/storage/',
	'/storage/*.key',
	'/vendor',
	'.env',
	'.env.backup',
	'.phpunit.result.cache',
	'Homestead.json',
	'Homestead.yaml',
	'npm-debug.log',
	'yarn-error.log',
	
	// WordPress
	'wp-config.php',
	'wp-content/uploads/',
	'wp-content/blogs.dir/',
	'wp-content/upgrade/',
	'wp-content/backup-db/',
	'wp-content/advanced-cache.php',
	'wp-content/wp-cache-config.php',
	'wp-content/cache/',
	'wp-content/cache/supercache/',
	'sitemap.xml',
	'sitemap.xml.gz',
	'*.log',
	
	// Mobile development
	'*.apk',
	'*.ap_',
	'*.dex',
	'*.class',
	'bin/',
	'gen/',
	'out/',
	'.gradle/',
	'build/',
	'local.properties',
	'proguard/',
	'*.log',
	
	// iOS
	'build/',
	'*.pbxuser',
	'!default.pbxuser',
	'*.mode1v3',
	'!default.mode1v3',
	'*.mode2v3',
	'!default.mode2v3',
	'*.perspectivev3',
	'!default.perspectivev3',
	'xcuserdata/',
	'*.xccheckout',
	'*.moved-aside',
	'DerivedData',
	'*.hmap',
	'*.ipa',
	'*.xcuserstate',
	'*.xcworkspace',
	
	// Unity
	'/[Ll]ibrary/',
	'/[Tt]emp/',
	'/[Oo]bj/',
	'/[Bb]uild/',
	'/[Bb]uilds/',
	'/[Ll]ogs/',
	'/[Mm]emoryCaptures/',
	'/[Uu]ser[Ss]ettings/',
	'*.tmp',
	'*.user',
	'*.userprefs',
	'*.pidb',
	'*.booproj',
	'*.svd',
	'*.pdb',
	'*.mdb',
	'*.opendb',
	'*.VC.db',
	'*.pidb.meta',
	'*.pdb.meta',
	'*.mdb.meta',
	'sysinfo.txt',
	'*.apk',
	'*.unitypackage',
	'Crashlytics/',
	
	// Database
	'*.sqlite',
	'*.sqlite3',
	'*.db',
	'*.db3',
	'*.s3db',
	'*.sl3',
	'*.mdb',
	'*.accdb',
	'*.dbf',
	'*.dump',
	'*.sql',
	
	// Docker
	'Dockerfile*',
	'docker-compose*.yml',
	'.dockerignore',
	
	// Kubernetes
	'*.yaml',
	'*.yml',
	'kustomization.yaml',
	
	// Terraform
	'*.tfstate',
	'*.tfstate.*',
	'crash.log',
	'*.tfvars',
	'override.tf',
	'override.tf.json',
	'*_override.tf',
	'*_override.tf.json',
	'.terraformrc',
	'terraform.rc',
	
	// Ansible
	'*.retry',
	'hosts',
	'group_vars/',
	'host_vars/',
	
	// Vagrant
	'.vagrant/',
	
	// JetBrains IDEs
	'.idea/',
	'*.iws',
	'*.iml',
	'*.ipr',
	'out/',
	'.idea_modules/',
	'atlassian-ide-plugin.xml',
	'com_crashlytics_export_strings.xml',
	'crashlytics.properties',
	'crashlytics-build.properties',
	'fabric.properties',
	
	// Eclipse
	'.metadata',
	'bin/',
	'tmp/',
	'*.tmp',
	'*.bak',
	'*.swp',
	'*~.nib',
	'local.properties',
	'.settings/',
	'.loadpath',
	'.recommenders',
	'.externalToolBuilders/',
	'*.launch',
	'.pydevproject',
	'.cproject',
	'.autotools',
	'.factorypath',
	'.buildpath',
	'.target',
	'.tern-project',
	'.texlipse',
	'.springBeans',
	'.recommenders/',
	'.apt_generated/',
	'.cache-main',
	'.scala_dependencies',
	'.worksheet'
]
